[default.database]
project = "d-dodeka"
service_name = "db"
container_name = "d-dodeka-db-1"
barman_server_name = "d-dodeka-db-1"
barman_backup_directory = "/dodeka_barman"
image_name = "dodeka/postgres"
version = "latest"
host_port = "3141"
container_port = "3141"
resources_source = "@format {env[HOME]}/postgres_host/db"
resources_target = "/dodeka-db"
volume_name = "db-volume"
network_name = "dodeka"
db_name = "dodeka"